# Generated by Django 4.1 on 2024-09-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayName', models.CharField(max_length=20)),
                ('dataType', models.CharField(max_length=20)),
                ('isActive', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('did', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'SOS_ATTRIBUTE',
            },
        ),
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collegeName', models.CharField(max_length=50)),
                ('collegeAddress', models.CharField(max_length=50)),
                ('collegeState', models.CharField(max_length=50)),
                ('collegeCity', models.CharField(max_length=20)),
                ('collegePhoneNumber', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'SOS_COLLEGE',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=50)),
                ('courseDescription', models.CharField(max_length=100)),
                ('courseDuration', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'SOS_COURSE',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField(max_length=20)),
                ('mobile', models.BigIntegerField(default=0)),
                ('expertise', models.CharField(max_length=50)),
                ('eid', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'SOS_DOCTOR',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('username', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('dob', models.DateField(max_length=20)),
                ('number', models.BigIntegerField(default='', max_length=50)),
            ],
            options={
                'db_table': 'SOS_EMPLOYEE',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.DateField(max_length=20)),
                ('college_ID', models.IntegerField()),
                ('collegeName', models.CharField(max_length=50)),
                ('subject_ID', models.IntegerField()),
                ('subjectName', models.CharField(max_length=50)),
                ('course_ID', models.IntegerField()),
                ('courseName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'SOS_FACULTY',
            },
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiativeName', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('startDate', models.CharField(max_length=20)),
                ('did', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'SOS_INITIATIVE',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openDate', models.DateField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('assignTo', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('sid', models.IntegerField(default=0)),
                ('aid', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'SOS_ISSUE',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=20)),
                ('contactname', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField(default=0)),
                ('status', models.CharField(max_length=50)),
                ('sid', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'SOS_LEAD',
            },
        ),
        migrations.CreateModel(
            name='Marksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNumber', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('physics', models.IntegerField()),
                ('chemistry', models.IntegerField()),
                ('maths', models.IntegerField()),
            ],
            options={
                'db_table': 'SOS_MARKSHEET',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(max_length=50)),
                ('product', models.CharField(max_length=50)),
                ('date', models.DateField(max_length=20)),
                ('amount', models.BigIntegerField(default=0)),
                ('pid', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'SOS_ORDER',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField(max_length=20)),
                ('vehicleId', models.IntegerField(default=0)),
                ('insuranceAmount', models.IntegerField(default=0)),
                ('did', models.IntegerField(default=0)),
                ('vid', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'SOS_OWNER',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('openDate', models.DateField(max_length=20)),
                ('version', models.CharField(max_length=20)),
                ('cid', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'SOS_PROJECT',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'SOS_ROLE',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('dob', models.DateField(max_length=20)),
                ('mobileNumber', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('college_ID', models.IntegerField()),
                ('collegeName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'SOS_STUDENT',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=50)),
                ('subjectDescription', models.CharField(max_length=50)),
                ('course_ID', models.IntegerField()),
                ('courseName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'SOS_SUBJECT',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateField(max_length=20)),
                ('taskTitle', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=200)),
                ('assignTo', models.CharField(max_length=50)),
                ('taskStatus', models.CharField(max_length=50)),
                ('aid', models.IntegerField(default=0)),
                ('sid', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'SOS_TASK',
            },
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examTime', models.CharField(max_length=40)),
                ('examDate', models.DateField()),
                ('subject_ID', models.IntegerField()),
                ('subjectName', models.CharField(max_length=50)),
                ('course_ID', models.IntegerField()),
                ('courseName', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'SOS_TIMETABLE',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('login_id', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('confirmpassword', models.CharField(default='', max_length=20)),
                ('dob', models.DateField(max_length=20)),
                ('address', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(default='', max_length=50)),
                ('mobilenumber', models.CharField(default='', max_length=50)),
                ('role_Id', models.IntegerField()),
                ('role_Name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'SOS_USER',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleId', models.IntegerField(max_length=50)),
                ('vehicleName', models.CharField(max_length=50)),
                ('vehicleType', models.CharField(max_length=50)),
                ('purchaseDate', models.DateField(max_length=20)),
                ('buyerName', models.CharField(max_length=20)),
                ('tid', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'SOS_VEHICLE',
            },
        ),
    ]
