# Generated by Django 4.1 on 2024-09-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffMember', models.CharField(max_length=20)),
                ('paymentAmount', models.BigIntegerField(default=0)),
                ('dateApplied', models.DateField(max_length=20)),
                ('state', models.CharField(max_length=50)),
                ('stid', models.IntegerField(default=0)),
                ('sid', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'SOS_COMPENSATION',
            },
        ),
    ]
