# Generated by Django 4.1 on 2024-09-20 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_portfoliomanagement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliomanagement',
            old_name='initialinvestmentLevel',
            new_name='initialInvestmentAmount',
        ),
    ]
