# Generated by Django 4.1 on 2024-09-28 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_rename_initialinvestmentlevel_portfoliomanagement_initialinvestmentamount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortfolioManagement',
        ),
    ]
