# Generated by Django 3.2.25 on 2025-01-08 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_delete_portfoliomanagement'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='college',
            table='sos_college',
        ),
        migrations.AlterModelTable(
            name='role',
            table='sos_role',
        ),
        migrations.AlterModelTable(
            name='user',
            table='sos_user',
        ),
    ]
